export type Task = {
  id: number;
  taskName: string;
  description?: string;
  duration: number;
  createdAt?: string;
  updatedAt?: string;
  projectId?: number;
  dependencies?: number[];
  level?: number;
  start?: number;
  end?: number;
  lateStart?: number;
  lateEnd?: number;
  slackTotal?: number;
  slackFree?: number;
  critical?: boolean;
  x?: number;
  y?: number;
};
